#! /bin/bash
#
# Autor: Bartosz Zawadka, 2016
#
# Contact: kontakt@bartoszzawadka.pl
#
# /etc/init.d/relayservice
#
### BEGIN INIT INFO
# Provides: relayservice
# Required-Start: $remote_fs $syslog $network
# Required-Stop: $remote_fs $syslog $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Relay state change service
# Description: Raspberry Pi relay manager service
### END INIT INFO

PIDFILE=/var/run/relay-service.pid
USER=root
CHUID=root
STARTAS=/usr/bin/python
ARGS=/home/pi/relayservice/main.py
RTIME=10

case "$1" in
	start)
 		echo "Starting service"
 		sudo start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --user $USER --chuid $CHUID --background --startas $STARTAS -- $ARGS
 		;;
 	stop)
 		echo "Stopping service"
 		sudo start-stop-daemon --stop --pidfile $PIDFILE --retry $RTIME --signal TERM
 		;;
 	restart)
 		echo "Restarting service"
 		$0 stop
 		$0 start
 		;;
 	*)
 		echo "Invalid command. Usage: /etc/init.d/relayservice {start|stop|restart}"
 		exit 1
 		;;
 esac

 exit 0
